# Generated by Django 3.1 on 2021-01-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digishop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
