# Generated by Django 3.1.5 on 2021-02-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digishop', '0004_auto_20210122_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
