# Generated by Django 3.1.5 on 2021-02-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digishop', '0005_auto_20210217_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='', verbose_name='uploads/thumbnail'),
        ),
    ]
