# Generated by Django 3.1.5 on 2021-02-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digishop', '0006_auto_20210219_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='staticfiles'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='', verbose_name='minishop/uploads/thumbnail'),
        ),
    ]
