# Generated by Django 3.1.5 on 2021-04-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digishop', '0011_auto_20210407_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='linkt',
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
